services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: app
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend-php
    ports:
      - "8081:8000"
    environment:
      DATABASE_URL: "postgresql://app:123@db:5432/app?serverVersion=16&charset=utf8"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-react
    ports:
      - "80:80"
    depends_on:
      - backend

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"      # accès depuis http://localhost:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  db-data:
  portainer_data: